export const ALL_METRICS = [
  'element',
  'event',
  'first-input',
  'largest-contentful-paint',
  'layout-shift',
  'longtask',
  'mark',
  'measure',
  'navigation',
  'paint',
  'resource',
  'taskattribution',
  'visibility-state',
];
